// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleManagement.API.Model.Context;

#nullable disable

namespace PeopleManagement.API.Migrations
{
    [DbContext(typeof(RmContext))]
    [Migration("20231013150809_InitializingDB")]
    partial class InitializingDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PeopleManagement.API.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<int>("CargoId")
                        .HasColumnType("int")
                        .HasColumnName("cargoid");

                    b.Property<DateTime>("DataDesligamento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("desligamento");

                    b.Property<DateTime>("DateAdmissao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("admissao");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("empresa");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int")
                        .HasColumnName("equipeid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("SetorId")
                        .HasColumnType("int")
                        .HasColumnName("setorid");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
