// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleManagement.API.Model.Context;

#nullable disable

namespace PeopleManagement.API.Migrations
{
    [DbContext(typeof(RmContext))]
    [Migration("20231014235615_InsertingData")]
    partial class InsertingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PeopleManagement.API.Model.Cargo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descricao");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("cargo");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descricao = "Engenheiro de Inovação",
                            Name = "Engenharia"
                        },
                        new
                        {
                            Id = 2L,
                            Descricao = "Coordenador Equipes",
                            Name = "Coordenador"
                        });
                });

            modelBuilder.Entity("PeopleManagement.API.Model.Equipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<int>("CoordenadorId")
                        .HasColumnType("int")
                        .HasColumnName("coordenadorId");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descricao");

                    b.Property<int>("GestorId")
                        .HasColumnType("int")
                        .HasColumnName("gestorId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("equipe");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CoordenadorId = 0,
                            Descricao = "Setor Inovação",
                            GestorId = 0,
                            Name = "Atenas"
                        },
                        new
                        {
                            Id = 2L,
                            CoordenadorId = 0,
                            Descricao = "Coordenador Equipes",
                            GestorId = 0,
                            Name = "Coordenador"
                        });
                });

            modelBuilder.Entity("PeopleManagement.API.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<int>("CargoId")
                        .HasColumnType("int")
                        .HasColumnName("cargoid");

                    b.Property<DateTime>("DataDesligamento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("desligamento");

                    b.Property<DateTime>("DateAdmissao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("admissao");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("empresa");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int")
                        .HasColumnName("equipeid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("SetorId")
                        .HasColumnType("int")
                        .HasColumnName("setorid");

                    b.HasKey("Id");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CargoId = 1,
                            DataDesligamento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateAdmissao = new DateTime(2023, 10, 14, 20, 56, 15, 247, DateTimeKind.Local).AddTicks(5937),
                            Empresa = "RM Mais Projetos",
                            EquipeId = 1,
                            Name = "Luan Bregunce",
                            SetorId = 1
                        },
                        new
                        {
                            Id = 2L,
                            CargoId = 1,
                            DataDesligamento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateAdmissao = new DateTime(2023, 10, 14, 20, 56, 15, 247, DateTimeKind.Local).AddTicks(5950),
                            Empresa = "RM Mais Projetos",
                            EquipeId = 1,
                            Name = "Carlos Eduardo",
                            SetorId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
